### ISSUE TITLE
Re-executing defnav calls doesn't update the routes

### ISSUE THREAD

**Issue by slyrus** [ritschmaster/caveman2-widgets-bootstrap#1]
re-executing defnav forms doesn't update the existing routes. If one manually setf's the route to null, re-executes the defnav form, and stops and starts the server, you can get the new pages served, but this seems like a lot of work.

**Comment by ritschmaster** [comment]
Thank you for your input!

This is actually an issue of [caveman2-widgets](https://github.com/ritschmaster/caveman2-widgets). I haven't figured out a way to do the navigation routing in a dynamic way.
